import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { roboto } from './ui/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <body
              className={`${roboto.className} antialiased secondary-color-700`}
          >
              {children}
          </body>
      </html>
  );
}
